version: '3.8'

services:
  petclinic:
    image: openjdk:17-jre-slim  # Using a generic OpenJDK image
    command: ["java", "-jar", "/app/spring-petclinic.jar"]
    ports:
      - "8080:8080"
    volumes:
      - ./path-to-your-local-jar:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
